"""Add ProductBrief, ModularScript, AIPersona models

Revision ID: 496f13ffbc93
Revises: add_page_fields_001
Create Date: 2026-03-23 22:28:04.339581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '496f13ffbc93'
down_revision: Union[str, Sequence[str], None] = 'add_page_fields_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_personas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('brand_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('visual_characteristics', sa.JSON(), nullable=True),
    sa.Column('voice_guidelines', sa.Text(), nullable=True),
    sa.Column('base_image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modular_scripts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('brand_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=True),
    sa.Column('intro_hook_type', sa.String(), nullable=True),
    sa.Column('intro_format', sa.String(), nullable=True),
    sa.Column('intro_text', sa.Text(), nullable=True),
    sa.Column('bridge_type', sa.String(), nullable=True),
    sa.Column('bridge_text', sa.Text(), nullable=True),
    sa.Column('core_type', sa.String(), nullable=True),
    sa.Column('core_text', sa.Text(), nullable=True),
    sa.Column('cta_type', sa.String(), nullable=True),
    sa.Column('cta_text', sa.Text(), nullable=True),
    sa.Column('naming_convention_code', sa.String(), nullable=True),
    sa.Column('performance_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modular_scripts_naming_convention_code'), 'modular_scripts', ['naming_convention_code'], unique=False)
    op.create_table('product_briefs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('target_audience', sa.Text(), nullable=True),
    sa.Column('primary_pain_points', sa.Text(), nullable=True),
    sa.Column('desired_outcomes', sa.Text(), nullable=True),
    sa.Column('root_causes_mechanisms', sa.Text(), nullable=True),
    sa.Column('proof_points', sa.Text(), nullable=True),
    sa.Column('differentiators', sa.Text(), nullable=True),
    sa.Column('risk_reversals', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_briefs')
    op.drop_index(op.f('ix_modular_scripts_naming_convention_code'), table_name='modular_scripts')
    op.drop_table('modular_scripts')
    op.drop_table('ai_personas')
    # ### end Alembic commands ###
