"""Add brief fields to product

Revision ID: e4a3aa80e0e5
Revises: 496f13ffbc93
Create Date: 2026-03-23 22:41:23.910779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4a3aa80e0e5'
down_revision: Union[str, Sequence[str], None] = '496f13ffbc93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_briefs')
    op.add_column('products', sa.Column('pain_points', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('desired_outcomes', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('root_causes', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('proof_points', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('differentiators', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('risk_reversals', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'risk_reversals')
    op.drop_column('products', 'differentiators')
    op.drop_column('products', 'proof_points')
    op.drop_column('products', 'root_causes')
    op.drop_column('products', 'desired_outcomes')
    op.drop_column('products', 'pain_points')
    op.create_table('product_briefs',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('target_audience', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('primary_pain_points', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('desired_outcomes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('root_causes_mechanisms', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('proof_points', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('differentiators', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('risk_reversals', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('product_briefs_product_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('product_briefs_pkey'))
    )
    # ### end Alembic commands ###
